using Microsoft.EntityFrameworkCore;
using Smithers.API.Data;
using Smithers.API.Models;

namespace Smithers.Tests;

/// <summary>
/// Creates a fresh AppDbContext backed by EF Core InMemory for each test.
/// Uses a unique db name per test to ensure full isolation.
/// </summary>
public static class TestDbFactory
{
    public static AppDbContext Create(string dbName)
    {
        var options = new DbContextOptionsBuilder<AppDbContext>()
            .UseInMemoryDatabase(dbName)
            // Disable the model validator that rejects three-part (schema.table.column) names,
            // which are generated by the SnakeCase convention + alternate key config in AppDbContext.
            .ConfigureWarnings(w => w.Ignore(Microsoft.EntityFrameworkCore.Diagnostics.InMemoryEventId.TransactionIgnoredWarning))
            .EnableServiceProviderCaching(false)
            .Options;

        return new AppDbContext(options);
    }

    // ── Shared seed helpers ────────────────────────────────────────────────

    public static Client SeedClient(AppDbContext ctx, string shortcode = "ACME", bool active = true)
    {
        var client = new Client
        {
            Id = Guid.NewGuid(),
            Shortcode = shortcode,
            CadenceName = $"{shortcode} Corp",
            Active = active,
            Dnc = false
        };
        ctx.Clients.Add(client);
        ctx.SaveChanges();
        return client;
    }

    public static ImportReviewQueue SeedQueueItem(AppDbContext ctx, string clientName = "ACME", string invoiceNumber = "INV-001", decimal amount = 1000m, string status = "Pending")
    {
        var item = new ImportReviewQueue
        {
            RunId = "run-test-" + Guid.NewGuid().ToString("N")[..8],
            RunTimestamp = DateTimeOffset.UtcNow,
            ClientName = clientName,
            DebtorName = "Some Debtor",
            InvoiceNumber = invoiceNumber,
            Amount = amount,
            ReviewStatus = status
        };
        ctx.ImportReviewQueue.Add(item);
        ctx.SaveChanges();
        return item;
    }

    public static Debtor SeedDebtor(AppDbContext ctx, string name = "Wayne Enterprises")
    {
        var debtor = new Debtor { Id = Guid.NewGuid(), Name = name, Group = "Active" };
        ctx.Debtors.Add(debtor);
        ctx.SaveChanges();
        return debtor;
    }

    public static Invoice SeedInvoice(
        AppDbContext ctx,
        string shortcode,
        Guid debtorId,
        string invoiceNumber = "INV-001",
        decimal amount = 1000m,
        string status = "Pre-Verified",
        int daysOld = 5)
    {
        var invoice = new Invoice
        {
            InvoiceId = $"{shortcode}_{invoiceNumber}",
            OriginalInvoice = invoiceNumber,
            Date = DateOnly.FromDateTime(DateTime.UtcNow.AddDays(-daysOld)),
            DebtorId = debtorId,
            LiquidClient = shortcode,
            Amount = amount,
            Status = status
        };
        ctx.Invoices.Add(invoice);
        ctx.SaveChanges();
        return invoice;
    }
}
