using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Smithers.API.Migrations
{
    /// <inheritdoc />
    public partial class AlignSchemaWithN8n : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "fk_import_review_queue_import_runs_run_id",
                table: "import_review_queue");

            migrationBuilder.DropIndex(
                name: "ix_import_review_queue_run_id",
                table: "import_review_queue");

            migrationBuilder.AddColumn<string>(
                name: "debtor_name",
                table: "invoices",
                type: "text",
                nullable: true);

            migrationBuilder.AlterColumn<string>(
                name: "run_id",
                table: "import_review_queue",
                type: "text",
                nullable: false,
                defaultValue: "",
                oldClrType: typeof(Guid),
                oldType: "uuid",
                oldNullable: true);

            migrationBuilder.AlterColumn<string>(
                name: "client_name",
                table: "import_review_queue",
                type: "text",
                nullable: false,
                defaultValue: "",
                oldClrType: typeof(string),
                oldType: "text",
                oldNullable: true);

            // uuid cannot be cast to bigint implicitly; drop PK + column and add fresh identity
            migrationBuilder.Sql("ALTER TABLE import_review_queue DROP CONSTRAINT pk_import_review_queue;");
            migrationBuilder.Sql("ALTER TABLE import_review_queue DROP COLUMN id;");
            migrationBuilder.Sql("ALTER TABLE import_review_queue ADD COLUMN id bigint GENERATED BY DEFAULT AS IDENTITY;");
            migrationBuilder.Sql("ALTER TABLE import_review_queue ADD CONSTRAINT pk_import_review_queue PRIMARY KEY (id);");

            migrationBuilder.AddColumn<string>(
                name: "all_debtors",
                table: "import_review_queue",
                type: "text",
                nullable: true);

            migrationBuilder.AddColumn<DateTimeOffset>(
                name: "created_at",
                table: "import_review_queue",
                type: "timestamp with time zone",
                nullable: false,
                defaultValue: new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)));

            migrationBuilder.AddColumn<string>(
                name: "invoice_date",
                table: "import_review_queue",
                type: "text",
                nullable: true);

            migrationBuilder.AddColumn<DateTimeOffset>(
                name: "run_timestamp",
                table: "import_review_queue",
                type: "timestamp with time zone",
                nullable: false,
                defaultValue: new DateTimeOffset(new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)));

            migrationBuilder.AddColumn<decimal>(
                name: "total_amount",
                table: "import_review_queue",
                type: "numeric",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "total_invoices",
                table: "import_review_queue",
                type: "integer",
                nullable: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropColumn(
                name: "debtor_name",
                table: "invoices");

            migrationBuilder.DropColumn(
                name: "all_debtors",
                table: "import_review_queue");

            migrationBuilder.DropColumn(
                name: "created_at",
                table: "import_review_queue");

            migrationBuilder.DropColumn(
                name: "invoice_date",
                table: "import_review_queue");

            migrationBuilder.DropColumn(
                name: "run_timestamp",
                table: "import_review_queue");

            migrationBuilder.DropColumn(
                name: "total_amount",
                table: "import_review_queue");

            migrationBuilder.DropColumn(
                name: "total_invoices",
                table: "import_review_queue");

            migrationBuilder.AlterColumn<Guid>(
                name: "run_id",
                table: "import_review_queue",
                type: "uuid",
                nullable: true,
                oldClrType: typeof(string),
                oldType: "text");

            migrationBuilder.AlterColumn<string>(
                name: "client_name",
                table: "import_review_queue",
                type: "text",
                nullable: true,
                oldClrType: typeof(string),
                oldType: "text");

            migrationBuilder.AlterColumn<Guid>(
                name: "id",
                table: "import_review_queue",
                type: "uuid",
                nullable: false,
                oldClrType: typeof(long),
                oldType: "bigint")
                .OldAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            migrationBuilder.CreateIndex(
                name: "ix_import_review_queue_run_id",
                table: "import_review_queue",
                column: "run_id");

            migrationBuilder.AddForeignKey(
                name: "fk_import_review_queue_import_runs_run_id",
                table: "import_review_queue",
                column: "run_id",
                principalTable: "import_runs",
                principalColumn: "id",
                onDelete: ReferentialAction.Cascade);
        }
    }
}
