// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Smithers.API.Data;

#nullable disable

namespace Smithers.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260602193456_AlignSchemaWithN8n")]
    partial class AlignSchemaWithN8n
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Smithers.API.Models.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("CadenceName")
                        .HasColumnType("text")
                        .HasColumnName("cadence_name");

                    b.Property<bool>("Dnc")
                        .HasColumnType("boolean")
                        .HasColumnName("dnc");

                    b.Property<string>("Shortcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("shortcode");

                    b.HasKey("Id")
                        .HasName("pk_clients");

                    b.HasAlternateKey("Shortcode")
                        .HasName("ak_clients_shortcode");

                    b.HasIndex("Shortcode")
                        .IsUnique()
                        .HasDatabaseName("ix_clients_shortcode");

                    b.ToTable("clients", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            Active = true,
                            CadenceName = "ACME Corp",
                            Dnc = false,
                            Shortcode = "ACME"
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            Active = true,
                            CadenceName = "Globex Corporation",
                            Dnc = false,
                            Shortcode = "GLOBEX"
                        });
                });

            modelBuilder.Entity("Smithers.API.Models.Debtor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("CadenceName")
                        .HasColumnType("text")
                        .HasColumnName("cadence_name");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("group");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("RedirectId")
                        .HasColumnType("uuid")
                        .HasColumnName("redirect_id");

                    b.HasKey("Id")
                        .HasName("pk_debtors");

                    b.HasIndex("RedirectId")
                        .HasDatabaseName("ix_debtors_redirect_id");

                    b.ToTable("debtors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Active = true,
                            CadenceName = "Wayne Ent",
                            Group = "Active",
                            Name = "Wayne Enterprises"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Active = true,
                            CadenceName = "Stark Ind",
                            Group = "Review",
                            Name = "Stark Industries"
                        });
                });

            modelBuilder.Entity("Smithers.API.Models.ImportReviewQueue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AllDebtors")
                        .HasColumnType("text")
                        .HasColumnName("all_debtors");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("client_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DebtorName")
                        .HasColumnType("text")
                        .HasColumnName("debtor_name");

                    b.Property<string>("InvoiceDate")
                        .HasColumnType("text")
                        .HasColumnName("invoice_date");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("text")
                        .HasColumnName("invoice_number");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid?>("ResolvedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_by");

                    b.Property<string>("ReviewStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("review_status");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("run_id");

                    b.Property<DateTimeOffset>("RunTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("run_timestamp");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("total_amount");

                    b.Property<int?>("TotalInvoices")
                        .HasColumnType("integer")
                        .HasColumnName("total_invoices");

                    b.HasKey("Id")
                        .HasName("pk_import_review_queue");

                    b.ToTable("import_review_queue", (string)null);
                });

            modelBuilder.Entity("Smithers.API.Models.ImportRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Matched")
                        .HasColumnType("integer")
                        .HasColumnName("matched");

                    b.Property<int>("RowCount")
                        .HasColumnType("integer")
                        .HasColumnName("row_count");

                    b.Property<DateTimeOffset>("RunDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("run_date");

                    b.Property<string>("SourceFile")
                        .HasColumnType("text")
                        .HasColumnName("source_file");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("Unmatched")
                        .HasColumnType("integer")
                        .HasColumnName("unmatched");

                    b.HasKey("Id")
                        .HasName("pk_import_runs");

                    b.ToTable("import_runs", (string)null);
                });

            modelBuilder.Entity("Smithers.API.Models.Invoice", b =>
                {
                    b.Property<string>("InvoiceId")
                        .HasColumnType("text")
                        .HasColumnName("invoice_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<bool>("Archived")
                        .HasColumnType("boolean")
                        .HasColumnName("archived");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<Guid>("DebtorId")
                        .HasColumnType("uuid")
                        .HasColumnName("debtor_id");

                    b.Property<string>("DebtorName")
                        .HasColumnType("text")
                        .HasColumnName("debtor_name");

                    b.Property<string>("DocumentPath")
                        .HasColumnType("text")
                        .HasColumnName("document_path");

                    b.Property<string>("LiquidClient")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasColumnName("liquid_client");

                    b.Property<string>("OriginalInvoice")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("original_invoice");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("InvoiceId")
                        .HasName("pk_invoices");

                    b.HasIndex("DebtorId")
                        .HasDatabaseName("ix_invoices_debtor_id");

                    b.HasIndex("LiquidClient", "OriginalInvoice")
                        .IsUnique()
                        .HasDatabaseName("ix_invoices_liquid_client_original_invoice");

                    b.ToTable("invoices", (string)null);
                });

            modelBuilder.Entity("Smithers.API.Models.InvoiceOcrResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("BboxHeight")
                        .HasColumnType("numeric(8,6)")
                        .HasColumnName("bbox_height");

                    b.Property<decimal?>("BboxWidth")
                        .HasColumnType("numeric(8,6)")
                        .HasColumnName("bbox_width");

                    b.Property<decimal?>("BboxX")
                        .HasColumnType("numeric(8,6)")
                        .HasColumnName("bbox_x");

                    b.Property<decimal?>("BboxY")
                        .HasColumnType("numeric(8,6)")
                        .HasColumnName("bbox_y");

                    b.Property<decimal?>("Confidence")
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("confidence");

                    b.Property<string>("ConfirmedValue")
                        .HasColumnType("text")
                        .HasColumnName("confirmed_value");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExtractedValue")
                        .HasColumnType("text")
                        .HasColumnName("extracted_value");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("field_name");

                    b.Property<string>("InvoiceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("invoice_id");

                    b.Property<int>("PageNumber")
                        .HasColumnType("integer")
                        .HasColumnName("page_number");

                    b.Property<bool>("Reviewed")
                        .HasColumnType("boolean")
                        .HasColumnName("reviewed");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by");

                    b.HasKey("Id")
                        .HasName("pk_invoice_ocr_results");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("ix_invoice_ocr_results_invoice_id");

                    b.ToTable("invoice_ocr_results", (string)null);
                });

            modelBuilder.Entity("Smithers.API.Models.Debtor", b =>
                {
                    b.HasOne("Smithers.API.Models.Debtor", "Redirect")
                        .WithMany()
                        .HasForeignKey("RedirectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_debtors_debtors_redirect_id");

                    b.Navigation("Redirect");
                });

            modelBuilder.Entity("Smithers.API.Models.Invoice", b =>
                {
                    b.HasOne("Smithers.API.Models.Debtor", "Debtor")
                        .WithMany()
                        .HasForeignKey("DebtorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_invoices_debtors_debtor_id");

                    b.HasOne("Smithers.API.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("LiquidClient")
                        .HasPrincipalKey("Shortcode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_invoices_clients_liquid_client");

                    b.Navigation("Client");

                    b.Navigation("Debtor");
                });

            modelBuilder.Entity("Smithers.API.Models.InvoiceOcrResult", b =>
                {
                    b.HasOne("Smithers.API.Models.Invoice", "Invoice")
                        .WithMany()
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_invoice_ocr_results_invoices_invoice_id");

                    b.Navigation("Invoice");
                });
#pragma warning restore 612, 618
        }
    }
}
