// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Smithers.API.Data;

#nullable disable

namespace Smithers.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260612195358_FixImportReviewQueueTimestampDefaults")]
    partial class FixImportReviewQueueTimestampDefaults
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Smithers.API.Models.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("CadenceName")
                        .HasColumnType("text")
                        .HasColumnName("cadence_name");

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("Contact")
                        .HasColumnType("text")
                        .HasColumnName("contact");

                    b.Property<decimal?>("DiscountRate")
                        .HasColumnType("numeric")
                        .HasColumnName("discount_rate");

                    b.Property<bool>("Dnc")
                        .HasColumnType("boolean")
                        .HasColumnName("dnc");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Language")
                        .HasColumnType("text")
                        .HasColumnName("language");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text")
                        .HasColumnName("postal_code");

                    b.Property<string>("Province")
                        .HasColumnType("text")
                        .HasColumnName("province");

                    b.Property<decimal?>("ReserveRate")
                        .HasColumnType("numeric")
                        .HasColumnName("reserve_rate");

                    b.Property<string>("Shortcode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("shortcode");

                    b.HasKey("Id")
                        .HasName("pk_clients");

                    b.HasAlternateKey("Shortcode")
                        .HasName("ak_clients_shortcode");

                    b.HasIndex("Shortcode")
                        .IsUnique()
                        .HasDatabaseName("ix_clients_shortcode");

                    b.ToTable("clients", (string)null);
                });

            modelBuilder.Entity("Smithers.API.Models.Debtor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("CadenceName")
                        .HasColumnType("text")
                        .HasColumnName("cadence_name");

                    b.Property<string>("City")
                        .HasColumnType("text")
                        .HasColumnName("city");

                    b.Property<string>("Contact")
                        .HasColumnType("text")
                        .HasColumnName("contact");

                    b.Property<bool>("Dnc")
                        .HasColumnType("boolean")
                        .HasColumnName("dnc");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("group");

                    b.Property<string>("Language")
                        .HasColumnType("text")
                        .HasColumnName("language");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text")
                        .HasColumnName("postal_code");

                    b.Property<string>("PreferredContactMethod")
                        .HasColumnType("text")
                        .HasColumnName("preferred_contact_method");

                    b.Property<string>("Province")
                        .HasColumnType("text")
                        .HasColumnName("province");

                    b.Property<Guid?>("RedirectId")
                        .HasColumnType("uuid")
                        .HasColumnName("redirect_id");

                    b.HasKey("Id")
                        .HasName("pk_debtors");

                    b.HasIndex("RedirectId")
                        .HasDatabaseName("ix_debtors_redirect_id");

                    b.ToTable("debtors", (string)null);
                });

            modelBuilder.Entity("Smithers.API.Models.ImportReviewQueue", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AllDebtors")
                        .HasColumnType("text")
                        .HasColumnName("all_debtors");

                    b.Property<decimal?>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("client_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DebtorName")
                        .HasColumnType("text")
                        .HasColumnName("debtor_name");

                    b.Property<string>("InvoiceDate")
                        .HasColumnType("text")
                        .HasColumnName("invoice_date");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("text")
                        .HasColumnName("invoice_number");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<Guid?>("ResolvedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("resolved_by");

                    b.Property<string>("ReviewStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("review_status");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("run_id");

                    b.Property<DateTimeOffset>("RunTimestamp")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("run_timestamp")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal?>("TotalAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("total_amount");

                    b.Property<int?>("TotalInvoices")
                        .HasColumnType("integer")
                        .HasColumnName("total_invoices");

                    b.HasKey("Id")
                        .HasName("pk_import_review_queue");

                    b.ToTable("import_review_queue", (string)null);
                });

            modelBuilder.Entity("Smithers.API.Models.ImportRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Matched")
                        .HasColumnType("integer")
                        .HasColumnName("matched");

                    b.Property<int>("RowCount")
                        .HasColumnType("integer")
                        .HasColumnName("row_count");

                    b.Property<DateTimeOffset>("RunDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("run_date");

                    b.Property<string>("SourceFile")
                        .HasColumnType("text")
                        .HasColumnName("source_file");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("Unmatched")
                        .HasColumnType("integer")
                        .HasColumnName("unmatched");

                    b.HasKey("Id")
                        .HasName("pk_import_runs");

                    b.ToTable("import_runs", (string)null);
                });

            modelBuilder.Entity("Smithers.API.Models.Invoice", b =>
                {
                    b.Property<string>("InvoiceId")
                        .HasColumnType("text")
                        .HasColumnName("invoice_id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric")
                        .HasColumnName("amount");

                    b.Property<bool>("Archived")
                        .HasColumnType("boolean")
                        .HasColumnName("archived");

                    b.Property<DateTimeOffset>("CreatedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_time");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<Guid>("DebtorId")
                        .HasColumnType("uuid")
                        .HasColumnName("debtor_id");

                    b.Property<string>("DebtorName")
                        .HasColumnType("text")
                        .HasColumnName("debtor_name");

                    b.Property<string>("DocumentPath")
                        .HasColumnType("text")
                        .HasColumnName("document_path");

                    b.Property<int>("FileCount")
                        .HasColumnType("integer")
                        .HasColumnName("file_count");

                    b.Property<string>("FlagReason")
                        .HasColumnType("text")
                        .HasColumnName("flag_reason");

                    b.Property<DateTimeOffset?>("FlagTimestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("flag_timestamp");

                    b.Property<bool>("Flagged")
                        .HasColumnType("boolean")
                        .HasColumnName("flagged");

                    b.Property<string>("LiquidClient")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasColumnName("liquid_client");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<string>("OriginalInvoice")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("original_invoice");

                    b.Property<DateTimeOffset?>("ProcessedTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_time");

                    b.Property<string>("ScheduleNumber")
                        .HasColumnType("text")
                        .HasColumnName("schedule_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int?>("Terms")
                        .HasColumnType("integer")
                        .HasColumnName("terms");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<bool>("Verified")
                        .HasColumnType("boolean")
                        .HasColumnName("verified");

                    b.HasKey("InvoiceId")
                        .HasName("pk_invoices");

                    b.HasIndex("DebtorId")
                        .HasDatabaseName("ix_invoices_debtor_id");

                    b.HasIndex("LiquidClient", "OriginalInvoice")
                        .IsUnique()
                        .HasDatabaseName("ix_invoices_liquid_client_original_invoice");

                    b.ToTable("invoices", (string)null);
                });

            modelBuilder.Entity("Smithers.API.Models.InvoiceOcrResult", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("BboxHeight")
                        .HasColumnType("numeric(8,6)")
                        .HasColumnName("bbox_height");

                    b.Property<decimal?>("BboxWidth")
                        .HasColumnType("numeric(8,6)")
                        .HasColumnName("bbox_width");

                    b.Property<decimal?>("BboxX")
                        .HasColumnType("numeric(8,6)")
                        .HasColumnName("bbox_x");

                    b.Property<decimal?>("BboxY")
                        .HasColumnType("numeric(8,6)")
                        .HasColumnName("bbox_y");

                    b.Property<decimal?>("Confidence")
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("confidence");

                    b.Property<string>("ConfirmedValue")
                        .HasColumnType("text")
                        .HasColumnName("confirmed_value");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("ExtractedValue")
                        .HasColumnType("text")
                        .HasColumnName("extracted_value");

                    b.Property<string>("FieldName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("field_name");

                    b.Property<string>("InvoiceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("invoice_id");

                    b.Property<int>("PageNumber")
                        .HasColumnType("integer")
                        .HasColumnName("page_number");

                    b.Property<bool>("Reviewed")
                        .HasColumnType("boolean")
                        .HasColumnName("reviewed");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("reviewed_by");

                    b.HasKey("Id")
                        .HasName("pk_invoice_ocr_results");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("ix_invoice_ocr_results_invoice_id");

                    b.ToTable("invoice_ocr_results", (string)null);
                });

            modelBuilder.Entity("Smithers.API.Models.Loan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("BorrowerName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("borrower_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("Guarantors")
                        .HasColumnType("text")
                        .HasColumnName("guarantors");

                    b.Property<decimal>("InterestRate")
                        .HasColumnType("numeric")
                        .HasColumnName("interest_rate");

                    b.Property<string>("LenderName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lender_name");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<decimal>("Principal")
                        .HasColumnType("numeric")
                        .HasColumnName("principal");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.HasKey("Id")
                        .HasName("pk_loans");

                    b.ToTable("loans", (string)null);
                });

            modelBuilder.Entity("Smithers.API.Models.LoanPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("LoanId")
                        .HasColumnType("uuid")
                        .HasColumnName("loan_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<decimal?>("OverrideInterest")
                        .HasColumnType("numeric")
                        .HasColumnName("override_interest");

                    b.Property<decimal?>("OverridePrincipal")
                        .HasColumnType("numeric")
                        .HasColumnName("override_principal");

                    b.Property<decimal>("PaymentAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("payment_amount");

                    b.Property<DateOnly>("PaymentDate")
                        .HasColumnType("date")
                        .HasColumnName("payment_date");

                    b.HasKey("Id")
                        .HasName("pk_loan_payments");

                    b.HasIndex("LoanId")
                        .HasDatabaseName("ix_loan_payments_loan_id");

                    b.ToTable("loan_payments", (string)null);
                });

            modelBuilder.Entity("Smithers.API.Models.NotificationSheet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AdvanceAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("advance_amount");

                    b.Property<decimal>("CashReservesToRelease")
                        .HasColumnType("numeric")
                        .HasColumnName("cash_reserves_to_release");

                    b.Property<string>("ClientShortcode")
                        .IsRequired()
                        .HasColumnType("character varying(50)")
                        .HasColumnName("client_shortcode");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("GcsIntakeObjectPath")
                        .HasColumnType("text")
                        .HasColumnName("gcs_intake_object_path");

                    b.Property<string>("GcsNsObjectPath")
                        .HasColumnType("text")
                        .HasColumnName("gcs_ns_object_path");

                    b.Property<decimal>("InitialFeePercent")
                        .HasColumnType("numeric")
                        .HasColumnName("initial_fee_percent");

                    b.Property<bool>("IsShared")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_shared");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<decimal>("OtherAdjustments")
                        .HasColumnType("numeric")
                        .HasColumnName("other_adjustments");

                    b.Property<decimal>("OtherFee")
                        .HasColumnType("numeric")
                        .HasColumnName("other_fee");

                    b.Property<decimal>("ReserveFeePercent")
                        .HasColumnType("numeric")
                        .HasColumnName("reserve_fee_percent");

                    b.Property<decimal>("ReservesToHoldBack")
                        .HasColumnType("numeric")
                        .HasColumnName("reserves_to_hold_back");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalFee")
                        .HasColumnType("numeric")
                        .HasColumnName("total_fee");

                    b.Property<decimal>("TotalReserve")
                        .HasColumnType("numeric")
                        .HasColumnName("total_reserve");

                    b.HasKey("Id")
                        .HasName("pk_notification_sheets");

                    b.HasIndex("ClientShortcode")
                        .HasDatabaseName("ix_notification_sheets_client_shortcode");

                    b.ToTable("notification_sheets", (string)null);
                });

            modelBuilder.Entity("Smithers.API.Models.NotificationSheetItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("IncludedAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("included_amount");

                    b.Property<string>("InvoiceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("invoice_id");

                    b.Property<Guid>("NotificationSheetId")
                        .HasColumnType("uuid")
                        .HasColumnName("notification_sheet_id");

                    b.Property<decimal?>("OverrideInitialFee")
                        .HasColumnType("numeric")
                        .HasColumnName("override_initial_fee");

                    b.Property<decimal?>("OverrideReserveFee")
                        .HasColumnType("numeric")
                        .HasColumnName("override_reserve_fee");

                    b.HasKey("Id")
                        .HasName("pk_notification_sheet_items");

                    b.HasIndex("InvoiceId")
                        .HasDatabaseName("ix_notification_sheet_items_invoice_id");

                    b.HasIndex("NotificationSheetId")
                        .HasDatabaseName("ix_notification_sheet_items_notification_sheet_id");

                    b.ToTable("notification_sheet_items", (string)null);
                });

            modelBuilder.Entity("Smithers.API.Models.StagedDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<string>("MatchJson")
                        .HasColumnType("text")
                        .HasColumnName("match_json");

                    b.Property<string>("OcrStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ocr_status");

                    b.Property<string>("ParsedFieldsJson")
                        .HasColumnType("text")
                        .HasColumnName("parsed_fields_json");

                    b.Property<string>("RawText")
                        .HasColumnType("text")
                        .HasColumnName("raw_text");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("storage_path");

                    b.HasKey("Id")
                        .HasName("pk_staged_documents");

                    b.HasIndex("BatchId")
                        .HasDatabaseName("ix_staged_documents_batch_id");

                    b.ToTable("staged_documents", (string)null);
                });

            modelBuilder.Entity("Smithers.API.Models.UploadBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClientShortcode")
                        .HasColumnType("text")
                        .HasColumnName("client_shortcode");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_upload_batches");

                    b.ToTable("upload_batches", (string)null);
                });

            modelBuilder.Entity("Smithers.API.Models.UserAccessRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<string>("ReviewedBySupabaseId")
                        .HasColumnType("text")
                        .HasColumnName("reviewed_by_supabase_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("UsernameWanted")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("username_wanted");

                    b.HasKey("Id")
                        .HasName("pk_user_access_requests");

                    b.ToTable("user_access_requests", (string)null);
                });

            modelBuilder.Entity("Smithers.API.Models.Debtor", b =>
                {
                    b.HasOne("Smithers.API.Models.Debtor", "Redirect")
                        .WithMany()
                        .HasForeignKey("RedirectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_debtors_debtors_redirect_id");

                    b.Navigation("Redirect");
                });

            modelBuilder.Entity("Smithers.API.Models.Invoice", b =>
                {
                    b.HasOne("Smithers.API.Models.Debtor", "Debtor")
                        .WithMany()
                        .HasForeignKey("DebtorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_invoices_debtors_debtor_id");

                    b.HasOne("Smithers.API.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("LiquidClient")
                        .HasPrincipalKey("Shortcode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_invoices_clients_liquid_client");

                    b.Navigation("Client");

                    b.Navigation("Debtor");
                });

            modelBuilder.Entity("Smithers.API.Models.InvoiceOcrResult", b =>
                {
                    b.HasOne("Smithers.API.Models.Invoice", "Invoice")
                        .WithMany()
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_invoice_ocr_results_invoices_invoice_id");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("Smithers.API.Models.LoanPayment", b =>
                {
                    b.HasOne("Smithers.API.Models.Loan", "Loan")
                        .WithMany("Payments")
                        .HasForeignKey("LoanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_loan_payments_loans_loan_id");

                    b.Navigation("Loan");
                });

            modelBuilder.Entity("Smithers.API.Models.NotificationSheet", b =>
                {
                    b.HasOne("Smithers.API.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientShortcode")
                        .HasPrincipalKey("Shortcode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_notification_sheets_clients_client_shortcode");

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Smithers.API.Models.NotificationSheetItem", b =>
                {
                    b.HasOne("Smithers.API.Models.Invoice", "Invoice")
                        .WithMany()
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_notification_sheet_items_invoices_invoice_id");

                    b.HasOne("Smithers.API.Models.NotificationSheet", "NotificationSheet")
                        .WithMany("Items")
                        .HasForeignKey("NotificationSheetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_notification_sheet_items_notification_sheets_notification_s");

                    b.Navigation("Invoice");

                    b.Navigation("NotificationSheet");
                });

            modelBuilder.Entity("Smithers.API.Models.StagedDocument", b =>
                {
                    b.HasOne("Smithers.API.Models.UploadBatch", "Batch")
                        .WithMany("Documents")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_staged_documents_upload_batches_batch_id");

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("Smithers.API.Models.Loan", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Smithers.API.Models.NotificationSheet", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Smithers.API.Models.UploadBatch", b =>
                {
                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
